name: ci

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            dist
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Set Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Set NPM version
        run: npm i -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: Generate dist
        run: npm start

  lint:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            dist
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run Eslint
        run: npm run lint

  unit-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            dist
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run Jest
        run: npm run test
